### ISSUE TITLE
get server IP

### ISSUE THREAD

**Issue by hennneh** [hennneh/ft_irc#31]
use getaddrinfo() and change it in functions: Welcome, motd, pass

**Comment by belgishboy** [comment]
also to function users and nick

**Comment by GQDeltex** [comment]
Since we haven't found a C/C++ function to get the hostname, we got creative and are now compiling in the hostname as a define via the Makefile which is running `hostname`. Not an ideal solution and could be considered cheating, but we haven't found a better one. Discussions with pedago are pending.
