### ISSUE TITLE
poll() before sending

### ISSUE THREAD

**Issue by hennneh** [hennneh/ft_irc#6]
checking if socket exists and if we can send

**Comment by GQDeltex** [comment]
Ask the `poll()` if the socket is available to write while asking if the socket is available to read. Maybe this might not even be necessary, we'll see.

**Comment by GQDeltex** [comment]
To add this we would have to add a flag to the client, if available to read/write. If so we could write into a buffer and send that as soon as the client is available to write again. But it still works, if we write into the fd even if the client is hanging, so I guess this issue is not relevant anymore
